chatdate/chat/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('chat.views',
    url(r'karma', 'karma', name="karma"),
)

chatdate/chatdate/urls.py
from django.conf.urls import patterns, include, url
from socketio import sdjango
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'chatdate.views.landingpage'),
    url(r'^relationships\.json$', 'relationship.views.relationships', name='relationships'),
    url(r'^chat/', include('chat.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r"^socket\.io", include(sdjango.urls)),
    url(r'^register$', 'chatdate.views.register_start', name='register_start'),
    url(r'^logout/$', 'chatdate.views.logout', name='logout'),
    url(r"^update_profile$", "chatdate.views.update_profile", name="update_profile"),
)

chatdate/chatdate/models.py
import datetime
import hashlib
from dateutil import parser

from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.contrib.gis.db import models
from django.contrib.gis.measure import D
import django.utils.timezone

SEXUAL_PEFERENCES = ((1, 'Heterosexual'), (2, 'Homosexual'), (3, 'Bisexual'))

class Picture(models.Model):
    caption = models.CharField(max_length=256)
    url = models.URLField()

class UserManager(models.GeoManager, BaseUserManager):
    def create_user(self, email, dob, nickname, full_name, password=None):
        dob = parser.parse(dob)
        u = self.create(email=email, dob=dob, nickname=nickname, full_name=full_name)
        u.set_password(password)
        u.save()
        return u

    def create_superuser(self, email, dob, nickname, full_name, password):
        u = self.create_user(email, dob, nickname, full_name, password)
        u.is_superuser = True
        u.save()
        return u


class User(AbstractBaseUser, PermissionsMixin, models.Model):
    gender = models.CharField("Your Gender", max_length=1, choices=(('M', "Male"), ("F", "Female")), default='M')
    transgendered = models.BooleanField("Transgendered?", default=False)
    sexual_preference = models.IntegerField("Your Sexual Orientation", choices=SEXUAL_PEFERENCES, default=1)
    nickname = models.CharField(max_length=25, help_text="Max 25 characters. Does not need to be unique.")
    full_name = models.TextField("Real Name", help_text="Only shown to those you choose.")
    email = models.EmailField(db_index=True, unique=True)
    relationships = models.ManyToManyField('self', through="relationship.Relationship", symmetrical=False)
    dob = models.DateField("Date of Birth", help_text="Format: YYYY-MM-DD")
    status = models.CharField(max_length=140)
    reputation = models.IntegerField(default=0)
    hash = models.CharField(max_length=32, db_index=True)
    location = models.PointField(help_text="Click and drag the marker to where you are located. Your exact coordinates will never be revealed to anyone.")
    specific_location = models.CharField("Location Description", help_text="You can be as spefific or vague as you wish. Example: Chelsea, Kentucky, South Miami.", max_length=50, blank=True)
    connection_distance = models.IntegerField(default=15, help_text="Users further than this amount of miles away from you will be ignored.")
    karma_threshold = models.IntegerField(default=0, help_text="Users with less karma than this value will be ignored")
    pics = models.ManyToManyField(Picture)

    show_straight_males = models.BooleanField(default=False)
    show_gay_males = models.BooleanField(default=False)
    show_bisexual_males = models.BooleanField(default=False)
    show_gay_females = models.BooleanField(default=False)
    show_straight_females = models.BooleanField(default=False)
    show_bisexual_females = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['dob', 'nickname', 'full_name']

    def age(self):
        today = datetime.date.today()
        born = self.dob
        try:
            birthday = born.replace(year=today.year)
        except ValueError: # raised when birth date is February 29 and the current year is not a leap year
            birthday = born.replace(year=today.year, day=born.day-1)
        if birthday > today:
            return today.year - born.year - 1
        else:
            return today.year - born.year

    def to_json(self):
        return {
            'nickname': self.nickname,
            'age': self.age(),
            'reputation': self.reputation,
            'hash': self.hash,
            'location': self.specific_location,
            'status': self.status,
            'gender': self.gender,
            'sexual_preference': self.sexual_preference
        } 

    @property
    def is_staff(self):
        return self.is_superuser

    def has_perm(self, perm, obj=None):
        return True if self.is_superuser else False

    def get_short_name(self):
        return self.nickname

    def is_authenticated(self):
        return True

    def set_default_prefs(self):
        """
        When a user first signs up, set their hiding preferences up based on their
        declared sexual preferences and gender.
        """
        if self.gender == 'M':
            self.show_gay_females = False
            self.show_straight_males = False
            
            if self.sexual_preference == 3: # bisexual male
                self.show_straight_females = True
                self.show_gay_males = True
                self.show_bisexual_females = True
                self.show_bisexual_males = True
            elif self.sexual_preference == 2: # gay male
                self.show_straight_females = False
                self.show_gay_males = True
                self.show_bisexual_females = False
                self.show_bisexual_males = True
            elif self.sexual_preference == 1: # straight male
                self.show_straight_females = True
                self.show_gay_males = False
                self.show_bisexual_females = True
                self.show_bisexual_males = False
        else: # a female
            self.show_gay_males = False
            self.show_straight_females = False
            
            if self.sexual_preference == 3: # bisexual female
                self.show_straight_males = True
                self.show_gay_females = True
                self.show_bisexual_females = True
                self.show_bisexual_males = True
            elif self.sexual_preference == 2: # gay female
                self.show_straight_males = False
                self.show_gay_females = True
                self.show_bisexual_females = True
                self.show_bisexual_males = False
            elif self.sexual_preference == 1: # straight female
                self.show_straight_males = True
                self.show_gay_females = False
                self.show_bisexual_females = False
                self.show_bisexual_males = True


    def apply_preference_excludes(self, qs):
        """
        Exclude users from a User queryset based on this user's hiding preferences.
        """
        if not self.show_gay_females:
            qs = qs.exclude(gender='F', sexual_preference=2)
        if not self.show_straight_males:
            qs = qs.exclude(gender='M', sexual_preference=1)
        if not self.show_straight_females:
            qs = qs.exclude(gender='F', sexual_preference=1)
        if not self.show_gay_males:
            qs = qs.exclude(gender='M', sexual_preference=2)
        if not self.show_bisexual_females:
            qs = qs.exclude(gender='F', sexual_preference=3)
        if not self.show_bisexual_males:
            qs = qs.exclude(gender='M', sexual_preference=3)

        return qs

    def cares_about(self, user):
        """
        Does this user care about chatting with the passed in user?
        """
        if user.gender == 'F':
            if user.sexual_preference == 1:
                return self.show_straight_females
            if user.sexual_preference == 2:
                return self.show_gay_females
            if user.sexual_preference == 3:
                return self.show_bisexual_females
        else:
            if user.sexual_preference == 1:
                return self.show_straight_males
            if user.sexual_preference == 2:
                return self.show_gay_males
            if user.sexual_preference == 3:
                return self.show_bisexual_males

    def save(self, *a, **k):
        if not self.hash:
            self.hash = hashlib.md5(self.email + settings.SECRET_KEY).hexdigest()

        hide_all = all([
            not self.show_straight_females, not self.show_gay_males,
            not self.show_gay_females, not self.show_straight_males,
            not self.show_bisexual_males, not self.show_bisexual_females
        ])

        if hide_all:
            # this should only happen when first signing up.
            self.set_default_prefs()

        super(User, self).save(*a, **k)

    def __unicode__(self):
        return "%s %s" % (self.get_sexual_preference_display(), self.get_gender_display())

    def local_users(self, online=False):
        """
        Return all users within my matching diatance preference.
        """
        #return User.objects.all()
        tup = (self.location, D(mi=9000)) #self.connection_distance))
        # .exclude(location__distance_lt=(self.location, models.F('connection_distance')))
        nearby = User.objects.filter(location__distance_lt=tup).exclude(id=self.id)

        nearby = self.apply_preference_excludes(nearby)

        if online:
            return nearby.filter(readytochat__isnull=False)
        else:
            return nearby

chatdate/chatdate/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class UserEditForm(forms.ModelForm):
    # old_password = forms.CharField(required=False, widget=forms.widgets.PasswordInput)
    # new_password = forms.CharField(required=False, widget=forms.widgets.PasswordInput)
    # new_password2 = forms.CharField(required=False, widget=forms.widgets.PasswordInput)

    # def clean(self):
    #     cleaned_data = super(UserEditForm, self).clean()
    #     if cleaned_data['new_password'] and not cleaned_data['new_password2']:
    #         raise forms.ValidationError("Must type new password twice")

    #     if cleaned_data['new_password2'] != cleaned_data['new_password']:
    #         raise forms.ValidationError("Passwords must match")

    #     if cleaned_data['new_password'] and not cleaned_data['old_password']:


    class Meta:
        model = User
        widgets = {
            'full_name': forms.TextInput,
            'location': forms.HiddenInput,
            'sexual_preference': forms.RadioSelect,
            'gender': forms.RadioSelect}
        exclude = ['user_permissions', 'password', 'groups', 'is_superuser', 'hash',
                   'last_login', 'relationships', 'status', 'reputation', 'pics',
                   'email', 'nickname']

class RegisterForm(forms.ModelForm):
    password_again = forms.CharField(widget=forms.widgets.PasswordInput)
    class Meta:
        widgets = {
            'password': forms.PasswordInput,
            'full_name': forms.TextInput,
            'location': forms.HiddenInput,
            'sexual_preference': forms.RadioSelect,
            'gender': forms.RadioSelect}
        model = User
        exclude = ['user_permissions', 'groups', 'is_superuser', 'hash', 'pics',
                  'connection_distance', 'karma_threshold',
                   'last_login', 'relationships', 'status', 'reputation']

chatdate/chatdate/views.py
import json
 
from django.template.response import TemplateResponse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth import logout as dj_logout

from .forms import RegisterForm, UserEditForm

def handle_upload(request):
    pass

def update_profile(request):
    form = UserEditForm(request.POST, instance=request.user)
    if form.is_valid():
        form.save()
        ret = "OK"
    else:
        ret = form.errors

    return HttpResponse(json.dumps(ret), mimetype="application/json")

def landingpage(request):
    """
    If user is logged in, return app.html, otherwise render the landingpge.
    Also, handle the login form.
    """
    if request.user.is_authenticated():
        profile_form = UserEditForm(instance=request.user)
        return TemplateResponse(request, 'app.html', locals())

    if request.POST:
        user = authenticate(username=request.POST['email'], password=request.POST['password'])
        if user:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            messages.error(request, 'Invalid Login')
    
    return TemplateResponse(request, 'landingpage.html', {})

def register_start(request):
    form = RegisterForm()
    status = 200
    if request.POST:
        form = RegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            new_user.set_password(new_user.password)
            new_user.save()
            user = authenticate(username=request.POST['email'], password=request.POST['password'])
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            status = 400

    return TemplateResponse(request, 'register.html', {'form': form}, status=status)

def logout(request):
    dj_logout(request)
    return HttpResponseRedirect('/')

chatdate/chatdate/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <!-- Set the viewport width to device width for mobile -->
        <meta name="viewport" content="width=device-width" />
        <meta charset="utf-8" />
        <title>{% block title %}SwoonLounge{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script src="{% static 'mustache.js' %}"></script>
        {% block extrahead %}{% endblock %}
    </head>
    <body>
        <header>
            <div id="left">
                <span class="logo">
                    <a href="/"><h1><span class="logo-red">Swoon</span><span class="logo-pink">Lounge</span></h1></a>
                </span>
                {% if user.is_authenticated %}
                | <a href="#" id="profile_link">Profile</a> |
                <a href="#" id="online_link">Who's Online</a> |
                <a href="#" id="relationships_link">Relationships</a> |
                <a href="{% url 'logout' %}">Logout</a>
                {% endif %}
            </div>
            <div id="right">
                <span class="logo">&nbsp;</span>
                {% if user.is_authenticated %}
                <span class="nickname">{{ user.nickname }}</span> (<span class="my_rep">{{ user.reputation }}</span>)
                {% endif %}
            </div>
        </header>
        <div id="content">
        {% block content %}{% endblock %}
        </div>
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-501381-14']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>
    </body>
</html>

chatdate/chatdate/templates/landingpage.html
{% extends "base.html" %}

{% block extrahead %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'landingpage.css' %}">
{% endblock %}

{% block content %}
<div id="center_content">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <p>
        SwoonLounge is an online community for meeting and chatting with other people in your area.
        Unlike other online dating sites where window shopping is the name of the game,
        SwoonLounge encourages interaction over compatibility matching algorithms.
        Currently SwoonLounge is in beta, so there aren't very many people to chat with on the site.
    </p>

    <h3>How it works</h3>

    <p>
        As you chat with other people, your karma score increases. People with higher karma
        gain more trust among other users of the site, and get to interact with more people.
    </p>

    <div id="login_form">
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            <label for="email">Email:</label> <input id="email" type="email" name="email">
            <label for="password">Password:</label> <input id="password" type="password" name="password">
            <input type="submit" value="Login"> or <a href="{% url "register_start" %}">Register</a>
        </form>
    </div>
</div>
{% endblock %}

chatdate/chatdate/templates/register.html
{% extends "base.html" %}

{% block extrahead %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'register.css' %}">
{% endblock %}

{% block content %}


<div id="center_content">
    <h1>Register New Account</h1>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBTQBbE5JzMZQIRb_RO6EwfnK_T5BvurNo&sensor=false"></script>
    <form method="post">
        {% csrf_token %}
        {{ form.errors }}
        <table>
            <tr>
                <th>{{ form.nickname.label_tag }}</th>
                <td>{{ form.nickname }}</td>
            </tr>
            <tr>
                <td></td>
                <td class="help">{{ form.nickname.help_text }}</td>
            </tr>

            <tr>
                <th>{{ form.email.label_tag }}</th>
                <td>{{ form.email }}</td>
            </tr>
            <tr>
                <td></td>
                <td class="help">{{ form.email.help_text }}</td>
            </tr>

            <tr>
                <th>{{ form.password.label_tag }}</th>
                <td>{{ form.password }}</td>
            </tr>
            <tr>
                <td></td>
                <td class="help">{{ form.password.help_text }}</td>
            </tr>
     
            <tr>
                <th>{{ form.password_again.label_tag }}</th>
                <td>{{ form.password_again }}</td>
            </tr>
            <tr>
                <td></td>
                <td class="help">{{ form.password_again.help_text }}</td>
            </tr>

            <tr>
                <th>{{ form.dob.label_tag }}</th>
                <td>{{ form.dob }}</td>
            </tr>
            <tr>
                <td></td>
                <td class="help">{{ form.dob.help_text }}</td>
            </tr>

            <tr>
                <th>{{ form.full_name.label_tag }}</th>
                <td>{{ form.full_name }}</td>
            </tr>
            <tr>
                <td></td>
                <td class="help">{{ form.full_name.help_text }}</td>
            </tr>

            <tr>
                <th>{{ form.gender.label_tag }}</th>
                <td>{{ form.gender }}</td>
            </tr>
            <tr>
                <td></td>
                <td class="help">{{ form.gender.help_text }}</td>
            </tr>

            <tr>
                <th>{{ form.transgendered.label_tag }}</th>
                <td>{{ form.transgendered }}</td>
            </tr>
            <tr>
                <td></td>
                <td class="help">{{ form.transgendered.help_text }}</td>
            </tr>

            <tr>
                <th>{{ form.sexual_preference.label_tag }}</th>
                <td>{{ form.sexual_preference }}</td>
            </tr>
            <tr>
                <td></td>
                <td class="help">{{ form.sexual_preference.help_text }}</td>
            </tr>

            <tr>
                <th>{{ form.location.label_tag }}</th>
                <td><div id="map_canvas"></div></td>
            </tr>
            <tr>
                <td></td>
                <td class="help">{{ form.location.help_text }}</td>
            </tr>

            <tr>
                <th>{{ form.specific_location.label_tag }}</th>
                <td>{{ form.specific_location }}</td>
            </tr>
            <tr>
                <td></td>
                <td class="help">{{ form.specific_location.help_text }}</td>
            </tr>
        </table>
        {{ form.location }}
        <input type="submit">
    </form>
</div>
<script type="text/javascript">
    function fill_in_wkt() {
        var loc = marker.getPosition();
        var wkt = "POINT(" + loc.lat() + ' ' + loc.lng() + ")";
        $("#id_location").val(wkt);
        console.log(wkt);
    }
    function place_marker(pos) {
        var latlng = new google.maps.LatLng(pos.coords.latitude, pos.coords.longitude)
        marker = new google.maps.Marker({
            position: latlng,
            map: map,
            draggable: true,
            title:"My Location"
        });
        google.maps.event.addListener(marker, 'dragend', function () {
            // when the marker is dragged around, update the form with
            // the markers new location
            fill_in_wkt();
        });
        fill_in_wkt()
        map.setCenter(latlng);
        console.log(pos.coords.latitude, pos.coords.longitude); 
    }

    var map, marker;
    $(function() {
        if(navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(place_marker);
        } else {
            place_marker({coords: {latitude: -34, longitude: 150}});
        }
        var mapOptions = {
            center: new google.maps.LatLng(-34.397, 150.644),
            zoom: 8,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map($("#map_canvas")[0], mapOptions);
    });
</script>

{% endblock %}